### PR TITLE
chore(secrets-client): Update default secrets API version to match the latest changes

### PR DESCRIPTION
**Pull request by joonas**
## Feature or Problem

Since we've landed on `v1alpha1` instead of `v0`, let's update the `secrets-client` to default to that as well.

### CODE REVIEW

**Review by protochron — APPROVED** [review]

**Review by vados-cosmonic — CHANGES_REQUESTED** [review]
Could you add `merge_group:` to the `secrets-nats-kv` workflow?

**Comment by joonas** [comment]
> Could you add `merge_group:` to the `secrets-nats-kv` workflow?

[`secrets-client` isn't currently part of that workflow](https://github.com/wasmCloud/wasmCloud/blob/main/.github/workflows/secrets-nats-kv.yml#L8-L13), but I can add it as part of this if you wanted to get it in there?

**Comment by vados-cosmonic** [comment]
Ahh yes -- it would be great if we could cover `secrets-client` under test if the tests aren't being run anywhere else right now!

**Review by brooksmtownsend — CHANGES_REQUESTED** [review]
@joonas this is captured in https://github.com/wasmCloud/wasmCloud/pull/2564, along with propagating the version down. I think the merge group change is still good

**Review by vados-cosmonic — APPROVED** [review]
LGTM :rocket:

**Comment by joonas** [comment]
> @joonas this is captured in #2564, along with propagating the version down. I think the merge group change is still good

Oh, doh. I thought I looked through every PR to make sure it wasn't already implemented somewhere. I'll close this out and make a separate PR for just the CI change.

**Pull request closed without merging**
