### PR TITLE
Add build, test and clippy checks to the project

### PR DESCRIPTION
**Pull request by billyoung**
This will add the basic testing suite to our workflow

### CODE REVIEW

**Comment by billyoung** [comment]
please hold. forgot a few things in this PR :)

**Comment by billyoung** [comment]
With the updates this accurately portrays our current tests/clippy results. If there is anything I am missing in our test suite please let me know.

**Comment by brooksmtownsend** [comment]
@billyoung Are the tests failing here expected, or is that something you're fixing?

**Review by brooksmtownsend — APPROVED** [review]
L G T M. Didn't know running a container is as easy as defining it under the `services` block, will have to keep that in mind for future actions

**Review by autodidaddict — APPROVED** [review]

**Comment by billyoung** [comment]
this was merged in #76 closing this PR

**Pull request closed without merging**
