### PR TITLE
fix(docs): fix incorrect links to rust examples

### PR DESCRIPTION
**Pull request by joshrotenberg**
## Feature or Problem

These links to Rust examples were pointing to the Go or 404.

### CODE REVIEW

**Comment by vados-cosmonic** [comment]
Hey @joshrotenberg thanks for making this contribution!

Would you mind adding DCO signoff? There are some [handy instructions here](https://github.com/wasmCloud/wasmCloud/pull/2571/checks?check_run_id=27890611671), but basically you should be able to run:

```
git commit --amend --signoff
```

**Review by vados-cosmonic — APPROVED** [review]
LGTM :rocket:

**Review by brooksmtownsend — APPROVED** [review]

**Comment by joshrotenberg** [comment]
Pre-coffee git shenanigans are a bad idea, let me know if this is ok. ☕

**Comment by vados-cosmonic** [comment]
Hey @joshrotenberg almost! I think the merge commits are the problem here (we do like `rebase`ing around these parts) -- but I think if you rebase to get rid of the merge commits you should be fine? 

This commit (https://github.com/wasmCloud/wasmCloud/pull/2571/commits/1393bfba4721a356b6bac69fb27e8c65b3c7617f) is DCO'd properly it looks like but the others aren't

**Comment by vados-cosmonic** [comment]
Oh also, you might want to click the "allow maintainers to make edits" checkbox as well -- that would help us help you in the future (well we can't sign off for you but a rebase or whatever)

**Comment by vados-cosmonic** [comment]
Thanks for getting this over the line @joshrotenberg !

**Pull request merged**
