### PR TITLE
chore(crates):  Replace actor references by component in crates

### PR DESCRIPTION
**Pull request by nitame**
## Feature or Problem
I wanted to rename `actor` references to `component` in the `crates` folder.
I started by renaming the crate `wasmcloud-actor` by `wasmcloud-component` and propagating modifications in other crates and tests.
I flag this PR to WIP because at the moment there is still work to do across the rust crates. Furthermore, there are still tests to fix (mainly from wash-cli crate).

## Related Issues
This is part of  Rename actor to component: #1827 

## Release Information
Could be part of the next release as soon as the PR is validated I guess.

## Consumer Impact
Rust crates which are owned and published by the wasmcloud project.

## Testing
WIP

### CODE REVIEW

**Review by brooksmtownsend — APPROVED** [review]
This is an awesome amount of work to do this rename! Tons of internal doc updates, though this PR also includes changes to public APIs and CLI output, so let's make sure to mark this as a breaking change to go out with the next minor release of wash/other crates.

This is releasable in a patch version of the host as it's not affecting any host output/flags

**Comment by thomastaylor312** [comment]
@nitame Would you mind signing off your commit?

**Comment by nitame** [comment]
> @nitame Would you mind signing off your commit?

Sure, I edited the commit message.

**Comment by nitame** [comment]
> This is an awesome amount of work to do this rename! Tons of internal doc updates, though this PR also includes changes to public APIs and CLI output, so let's make sure to mark this as a breaking change to go out with the next minor release of wash/other crates.
> 
> This is releasable in a patch version of the host as it's not affecting any host output/flags

I pushed one more little change since you approved the changes. I renamed the struct Actor by Component in the file `crates/component/src/lib.rs`.

As it is already a lot of changes, I think I will make another PR to replace the remaining references to `actor` from the crates.

@brooksmtownsend how do I mark this as a breaking change?

**Comment by nitame** [comment]
@brooksmtownsend Thank you for the explanations. I rebased the branch on main and marked it `Ready for Review`.

**Comment by brooksmtownsend** [comment]
@nitame sorry about this, I didn't merge this in time and it looks like there's a couple more conflicts. Would you mind giving this a rebase, or do you mind if I just rebase it and merge after? This is all approved it just needs those conflicts resolved and I'll press the button 😄

**Comment by nitame** [comment]
@brooksmtownsend no worries 😄 I rebased and resolved conflicts.

**Comment by thomastaylor312** [comment]
Talked to @brooksmtownsend and merging for him

**Comment by brooksmtownsend** [comment]
Thank you @nitame !

**Pull request merged**
