### PR TITLE
chore(examples): remove examples cargo lock

### PR DESCRIPTION
**Pull request by vados-cosmonic**
This commit removes the `Cargo.lock` for `http-blobstore` that was likely accidentally checked in, and adds a `.cargo/config.toml` so that the project can be built with `cargo build`.

### CODE REVIEW

**Review by rvolosatovs — CHANGES_REQUESTED** [review]
I'm not sure that's what we want. (also note that every example has a `Cargo.lock`)

We should only remove the `Cargo.lock` if we make the example part of the workspace (which would prevent it from being built as part of the tests)

**Review by rvolosatovs — COMMENTED** [review]
How about we make all example components part of the same workspace instead, removing `Cargo.lock` for all examples and just have one shared one in the workspace?

This way we would have 3 workspaces in the repo and hopefully speed up builds

**Comment by vados-cosmonic** [comment]
@rvolosatovs we don't *check in* `Cargo.lock` for any other example, why do you want it to persist for this one?

**Comment by brooksmtownsend** [comment]
@rvolosatovs The main downside for examples being a part of the workspace is when we generate them as a part of creating a new project template, then the examples don't stand by themselves. Outside of the ones that we generate as templates I'm fine with the workspace, though

**Review by rvolosatovs — APPROVED** [review]
yeah, you're we don't have `Cargo.lock`s checked in for other examples, I was confused.

Still probably best to make all components part of a single workspace

**Comment by vados-cosmonic** [comment]
> Still probably best to make all components part of a single workspace

Agree with that! Also @brooksmtownsend 's poitn is good, I think the `Cargo.lock` would get overriden instantly in a new template project, but not having it is nice as well. 

AFAIK we shouldn't make this change for `tests/components` because that really is another workspace sort of hidden inside the top level one, but this one seemed reasonable. Thanks for looking at it closely!

**Comment by rvolosatovs** [comment]
> @rvolosatovs The main downside for examples being a part of the workspace is when we generate them as a part of creating a new project template, then the examples don't stand by themselves. Outside of the ones that we generate as templates I'm fine with the workspace, though

sounds good, let's discuss and address in a separate PR/issue

**Pull request merged**
