### PR TITLE
chore(deps): update example (local.)wadm.yaml and readme files

### PR DESCRIPTION
**Pull request by joonas**
This PR contains the following updates:

| Package | Update | Change |
|---|---|---|
| ghcr.io/wasmcloud/blobstore-fs | patch | `0.10.1` -> `0.10.2` |
| ghcr.io/wasmcloud/components/http-jsonify-rust | patch | `0.1.1` -> `0.1.2` |
| ghcr.io/wasmcloud/http-server | minor | `0.23.2` -> `0.25.0` |
| ghcr.io/wasmcloud/http-server | minor | `0.24.0` -> `0.25.0` |
| ghcr.io/wasmcloud/http-server | minor | `0.22.0` -> `0.25.0` |
| ghcr.io/wasmcloud/keyvalue-redis | patch | `0.28.1` -> `0.28.2` |
| ghcr.io/wasmcloud/messaging-nats | minor | `0.23.1` -> `0.24.0` |
| ghcr.io/wasmcloud/sqldb-postgres | patch | `0.7.1` -> `0.7.2` |

---

> [!WARNING]
> Some dependencies could not be looked up. Check the Dependency Dashboard for more information.

---

### Configuration

📅 **Schedule**: Branch creation - At any time (no schedule defined), Automerge - At any time (no schedule defined).

🚦 **Automerge**: Disabled by config. Please merge this manually once you are satisfied.

♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the rebase/retry checkbox.

👻 **Immortal**: This PR will be recreated if closed unmerged. Get [config help](https://redirect.github.com/renovatebot/renovate/discussions) if that's undesired.

---

 - [ ] If you want to rebase/retry this PR, check this box

---

This PR has been generated by [Renovate Bot](https://redirect.github.com/renovatebot/renovate).

### CODE REVIEW

**Comment by markkovari** [comment]
Other than the missing signature this is looking good. 🕺 💃 
If anyone has better ideas for the commit name and the other configs in the [config file](https://github.com/wasmCloud/wasmCloud/blob/main/.github/renovate.json) please add a PR. 🎉

**Comment by joonas** [comment]
### Edited/Blocked Notification

Renovate will not automatically rebase this PR, because it does not recognize the last commit author and assumes somebody else may have edited the PR.

You can manually request rebase by checking the rebase/retry box above.

 ⚠️ **Warning**: custom changes will be lost.

**Comment by lachieh** [comment]
@joonas should these be commenting as you or the github bot?

**Comment by joonas** [comment]
@lachieh these are intended to be coming from [`wasmcloud-automation-app[bot]`](https://github.com/wasmCloud/wasmCloud/pull/3830) and [`github-actions[bot]`](https://github.com/wasmCloud/wasmCloud/pull/3824), but the latter PR is still open so I haven't closed this out so as to not have it get re-created under my user.

**Comment by joonas** [comment]
Now that https://github.com/wasmCloud/wasmCloud/pull/3830 has landed, I'm going to close this and let renovate bot re-created it with the app token

**Pull request closed without merging**
