### PR TITLE
feat(provider-sdk): name the provider's NATS connection

### PR DESCRIPTION
**Pull request by joonas**
## Feature or Problem

This will make it easier to figure out which connection might be associated with what provider.

For illustrative example, compare the before and after outputs:

Before:
```
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                Top 3 Connections out of 3 by subs                                                                               │
├─────┬──────────────────────────────┬──────────────────────────────────────────────────────────┬─────────┬─────────────────┬─────────┬────────┬─────────┬──────────┬──────────┬───────────┬──────┤
│ CID │ Name                         │ Server                                                   │ Cluster │ IP              │ Account │ Uptime │ In Msgs │ Out Msgs │ In Bytes │ Out Bytes │ Subs │
├─────┼──────────────────────────────┼──────────────────────────────────────────────────────────┼─────────┼─────────────────┼─────────┼────────┼─────────┼──────────┼──────────┼───────────┼──────┤
│ 74  │ NATS CLI Version development │ NDH6X64JI7RN2HOCH2FCG2X5MQ4DC24NG7DSLZ2YRV5MQGONJIALL7UD │         │ 127.0.0.1:53931 │         │ 0s     │ 1       │ 0        │ 254 B    │ 0 B       │ 1    │
│ 73  │ test-client                  │ NDH6X64JI7RN2HOCH2FCG2X5MQ4DC24NG7DSLZ2YRV5MQGONJIALL7UD │         │ ::1:53930       │         │ 0s     │ 1       │ 0        │ 5 B      │ 0 B       │ 2    │
│ 69  │                              │ NDH6X64JI7RN2HOCH2FCG2X5MQ4DC24NG7DSLZ2YRV5MQGONJIALL7UD │         │ ::1:53926       │         │ 3s     │ 0       │ 0        │ 0 B      │ 0 B       │ 5    │
├─────┼──────────────────────────────┼──────────────────────────────────────────────────────────┼─────────┼─────────────────┼─────────┼────────┼─────────┼──────────┼──────────┼───────────┼──────┤
│     │ TOTALS FOR 3 CONNECTIONS     │                                                          │         │                 │         │        │ 2       │ 0        │ 259 B    │ 0 B       │ 8    │
╰─────┴──────────────────────────────┴──────────────────────────────────────────────────────────┴─────────┴─────────────────┴─────────┴────────┴─────────┴──────────┴──────────┴───────────┴──────╯
```

After:

```
╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                Top 3 Connections out of 3 by subs                                                                                │
├─────┬───────────────────────────────┬──────────────────────────────────────────────────────────┬─────────┬─────────────────┬─────────┬────────┬─────────┬──────────┬──────────┬───────────┬──────┤
│ CID │ Name                          │ Server                                                   │ Cluster │ IP              │ Account │ Uptime │ In Msgs │ Out Msgs │ In Bytes │ Out Bytes │ Subs │
├─────┼───────────────────────────────┼──────────────────────────────────────────────────────────┼─────────┼─────────────────┼─────────┼────────┼─────────┼──────────┼──────────┼───────────┼──────┤
│ 99  │ NATS CLI Version development  │ NDH6X64JI7RN2HOCH2FCG2X5MQ4DC24NG7DSLZ2YRV5MQGONJIALL7UD │         │ 127.0.0.1:53964 │         │ 0s     │ 1       │ 0        │ 254 B    │ 0 B       │ 1    │
│ 98  │ test-client                   │ NDH6X64JI7RN2HOCH2FCG2X5MQ4DC24NG7DSLZ2YRV5MQGONJIALL7UD │         │ ::1:53963       │         │ 0s     │ 1       │ 0        │ 5 B      │ 0 B       │ 2    │
│ 94  │ blobstore-azure-provider-test │ NDH6X64JI7RN2HOCH2FCG2X5MQ4DC24NG7DSLZ2YRV5MQGONJIALL7UD │         │ ::1:53959       │         │ 3s     │ 0       │ 0        │ 0 B      │ 0 B       │ 5    │
├─────┼───────────────────────────────┼──────────────────────────────────────────────────────────┼─────────┼─────────────────┼─────────┼────────┼─────────┼──────────┼──────────┼───────────┼──────┤
│     │ TOTALS FOR 3 CONNECTIONS      │                                                          │         │                 │         │        │ 2       │ 0        │ 259 B    │ 0 B       │ 8    │
╰─────┴───────────────────────────────┴──────────────────────────────────────────────────────────┴─────────┴─────────────────┴─────────┴────────┴─────────┴──────────┴──────────┴───────────┴──────╯
````

### CODE REVIEW

**Review by rvolosatovs — APPROVED** [review]

**Comment by rvolosatovs** [comment]
We should probably also do this for the host (and use the host ID as the name?)

**Comment by joonas** [comment]
> We should probably also do this for the host (and use the host ID as the name?)

Definitely should, I'm not clear what would be the most useful thing to put in there, but ideally it's something that could be quickly scanned and correlated against other data.

**Review by brooksmtownsend — APPROVED** [review]

**Comment by brooksmtownsend** [comment]
> Definitely should, I'm not clear what would be the most useful thing to put in there, but ideally it's something that could be quickly scanned and correlated against other data.

Host friendly name would be a great addition here imo. We could do the host ID as well, but that's going to get confusing because the NATS CLI output also includes the server ID 😄

**Review by protochron — APPROVED** [review]
We should probably go into our first party provider code and prepend `wasmCloud` or something. Ex. `wasmCloud blobstore provider azure` makes more sense at first glance with the prefix than without it.

**Pull request merged**
