### PR TITLE
chore(wash-cli, wash-lib) remove async nats 033

### PR DESCRIPTION
**Pull request by vados-cosmonic**

### CODE REVIEW

**Comment by vados-cosmonic** [comment]
Note: this PR is held up by a release of `wadm-types` that is the last bastion of `async nats 0.33.0` usage in our codebase!

**Review by brooksmtownsend — APPROVED** [review]
Woo!

**Comment by brooksmtownsend** [comment]
@vados-cosmonic heads up I removed this, because the test was failing

**Review by brooksmtownsend — APPROVED** [review]
As a ci-maintainer, I approve this PR

**Comment by vados-cosmonic** [comment]
Blocked on https://github.com/wasmCloud/wasmCloud/pull/3209

**Review by thomastaylor312 — APPROVED** [review]

**Pull request merged**
