### PR TITLE
Fix #1724 - TypeScript Hello World example fails to build

### LINKED ISSUE #1724: [BUG] TypeScript Hello World example fails to build
### Affected project(s)

- [ ] documentation
- [X] examples
- [ ] wasmCloud host
- [ ] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [ ] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Describe the bug

The TypeScript Hello World example fails to build while following the doc, the `wash build` command fails with an error:

```bash
$ wash build

failed to build actor with custom command: "Error: The package \"@bytecodealliance/wizer-linux-x64\" could not be found, and is needed by @bytecodealliance/wizer.\nIf you are installing @bytecodealliance/wizer with npm, make sure that you don't specify the\n\"--no-optional\" flag. The \"optionalDependencies\" package.json feature is used\nby @bytecodealliance/wizer to install the correct binary executable for your current platform.\n    at file:///home/horacio/git/wasmcloud/hello/node_modules/@bytecodealliance/wizer/index.js:11:9\n"
```

### Steps to reproduce

1. Create the project
    ```bash
    wash new component hello --template-name hello-world-typescript
    ```
1. Execute `npm install`
1. Try to build with `wash build` 

### Expected behavior

The project building without problem

### Environment

- OS: Linux Fedora 39
- Shell: bash
- wasmcloud version: wash 0.27.0-alpha.1

### Screenshots / Logs / Additional context

_No response_

### PR DESCRIPTION
**Pull request by LostInBrittany**
## Feature or Problem

The TypeScript Hello World example fails to build on linux while following the doc, the `wash build` command file as the system-linked dependence of `@bytecodealliance/wizer` is fixed to `wizer-darwin-arm64` (for Apple Silicon Macs).

Removing the `package-lock.json` forces the `npm i` to look and recover the right dependence for the system used to build.

## Related Issues

This PR fixes the issue explained in #1724. 

## Release Information

Next release

## Consumer Impact

No impact besides this example

### Manual Verification

To verify it works as intended, you can simple create the project from the example template with `wash new component hello --template-name hello-world-typescript`, delete `package-lock.json`, install with `npm i` and build with `wash build` in any supported system.

### CODE REVIEW

**Review by rvolosatovs — APPROVED** [review]
Thanks!

**Review by brooksmtownsend — DISMISSED** [review]
Hey @LostInBrittany , looks like this removed the package.json, would you mind removing the lock file and pushing that instead?

**Comment by LostInBrittany** [comment]
Ouch, I erased the bad file? Sorry ! Repushing...

**Review by rvolosatovs — APPROVED** [review]

**Review by thomastaylor312 — APPROVED** [review]

**Comment by thomastaylor312** [comment]
Thanks for the fix @LostInBrittany!

**Pull request merged**
