### PR TITLE
feat: Improved the output of wash get inventory command, as outlined in issue #2398

### PR DESCRIPTION
**Pull request by ossfellow**
## Feature or Problem
This PR improves the output of `wash get inventory` command.

## Related Issues
[Issue #2398](https://github.com/wasmCloud/wasmCloud/issues/2398)

## Testing
The new output format has been tested locally.

### CODE REVIEW

**Comment by vados-cosmonic** [comment]
Hey @ossfellow sorry for the delay! Would you mind adding a test to this PR?

I think one of the things @brooksmtownsend was really trying to get at was the fact that when we had a long component ref (ex. `ghcr.io/some/repository/with/a/component/in/it:0.3.0`), it would make the regular non-JSON output unreadable due to line wrapping. 

It would be awesome if we had a test that was *exactly* that case -- just checking the lines in stdout would be enough. You could mostly copy https://github.com/wasmCloud/wasmCloud/blob/main/crates/wash-cli/tests/wash_get.rs#L75 (that's probably also where the test should go), and we could get a nice regression test for this!

**Comment by vados-cosmonic** [comment]
Oh and BTW the fix to the integration tests should be merged soon -- so if you wouldn't mind clicking the "allow edits by maintainers" checkbox, we can rebase in one click from this side before merging!

**Comment by ossfellow** [comment]
@vados-cosmonic, I can certainly add the test and let maintainers update the PR (which I thought is the default); I'll be back at my desk in a couple of hours and will do what you've suggested.
Thanks for the test sample btw.

**Comment by ossfellow** [comment]
> Hey @ossfellow sorry for the delay! Would you mind adding a test to this PR?
> 
> I think one of the things @brooksmtownsend was really trying to get at was the fact that when we had a long component ref (ex. `ghcr.io/some/repository/with/a/component/in/it:0.3.0`), it would make the regular non-JSON output unreadable due to line wrapping.
> 
> It would be awesome if we had a test that was _exactly_ that case -- just checking the lines in stdout would be enough. You could mostly copy https://github.com/wasmCloud/wasmCloud/blob/main/crates/wash-cli/tests/wash_get.rs#L75 (that's probably also where the test should go), and we could get a nice regression test for this!

Hello @vados-cosmonic, based on the requirement, I have removed the `component ref` from the non-JSON output; so, could you please clarify if you want me to add a test for the JSON output, or any of the attributes of the non-JSON output?

Also, the option to allow maintainers edit the PR doesn't show under the list of PR participants; if this isn't due to a project rule, maybe converting the PR to draft will make it work, although I'm not sure to be honest.

Once you clarify, I'll add the test and update the PR.

**Comment by vados-cosmonic** [comment]
Hey @ossfellow that's a good point -- so I think we might want to solve that a slightly different way... Rather than *remove* the `ref`, we might want to shorten/length constrain it (ellipses?)... And we definitely don't want it out of the JSON output, because that is probably used for machines to read and we want to provide as much information as possible (might even break some tests we have now). 

Oh and if it isn't there then don't worry about it I guess! Not sure why it wouldn't show up!

**Comment by ossfellow** [comment]
@vados-cosmonic, there seems to be a difference of opinions over what should be in the table formatted output of the `wash get inventory` command.

While I'm not against adding the `image_ref` back in the output, may I ask you to speak to @brooksmtownsend and update the issue this PR is referencing, for the sake of consistency?

If it's decided to add it back in, I'll only add the file name and drop the path.

Also, please note that the json output is left intact, as the ask was for the table output.

**Comment by vados-cosmonic** [comment]
Hey @ossfellow I see what you meant!

Oh you're right @brooksmtownsend wanted to remove the image reference completely, as it says in the issue:

>  with wash displaying the full image reference really just isn't quite necessary.

I think based on what's in the issue you've absolutely solved the problem, but it would be nice to have some way to make sure that the inventory command doesn't overflow again, given possibly long out put for any of those other fields... 

For example I'm thinking what if I make a really long friendly name -- do things go off the rails then?

What do you think?

> Also, please note that the json output is left intact, as the ask was for the table output.

Great, thank you!

**Comment by ossfellow** [comment]
Hey @vados-cosmonic, it's possible that _name_, or _label_ fields could potentially get longer that the width of output window; but all the variables (i.e. what name to use, what labels to use, and output window size) are user selected, and I'm not if, on the _wash cli_ side, we could, or even should, force anything on the user.
I think the intent of the issue Brooks created has been to minimize the chance of output line wrapping, without being prescriptive about user choices.

Nonetheless, I'm totally open to any suggestions, which could improve the user experience.

**Review by brooksmtownsend — APPROVED** [review]
This looks great to me! Likely just needs a rebase to bring in some of the latest changes to fix tests. @ossfellow I can take care of this if you'd like, just let me know, otherwise I will wait for your rebase 😄 

I know that there's probably some smart things we can do, especially around names, in order to wrap longer names, but I think that can be an optimization we make when we want to be a bit smarter with the table. This should really help 95% of the host inventories look better

**Comment by vados-cosmonic** [comment]
Hey @ossfellow would you mind rebasing this PR to `main` if it isn't already? not sure why CI is stuck...

I'll mark it "merge when ready" so that it can merge as soon as checks pass.

**Comment by ossfellow** [comment]
I did rebase it last night and the PR is showing up to date on GitHub (which as you know will show if it isn’t).
As a lost resort, if the CI remains stuck, I can close the PR and issue a new one; but hopefully we won’t get there.

**Comment by brooksmtownsend** [comment]
Trying to get GHA to trigger.

**Pull request merged**
