### PR TITLE
Implemented feature flags for wasmcloud binary

### PR DESCRIPTION
**Pull request by brooksmtownsend**
This PR allows you to run the wasmcloud binary with either the `wasm3` or `wasmtime` engine. The default is wasm3, and in order to run with wasmtime you must use the following command:
```
cargo run --features wasmtime --no-default-features
```
In order to enforce a default, as @ChrisRx noted in #56, we have to explicitly remove the default feature in order to use the other engine type. I've adjusted the default log verbosity for the `wasmtime-provider` as in `info` mode you will get a lot of output as wasmtime JITs the actor module, in `debug` mode you get an unusable amount of wasm debug output.

This PR also uncomments our integration tests.

### CODE REVIEW

**Comment by billyoung** [comment]
@brooksmtownsend are we happy with the default `wasm3` being packaged into our deb/rpm packages? If a customer wants to use `wasmtime` I assume they would have to compile and package themselves?

**Comment by brooksmtownsend** [comment]
@billyoung Yeah that's correct, everything will be packaged as wasm3 (which is what we were doing before). We could certainly just adjust the default, or even just the release action to release wasmtime, but I don't think it's necessary to publish both engines as a binary (at least for now when both engines are essentially the same). ADR time for default wasm engine for published binary? @autodidaddict

**Comment by brooksmtownsend** [comment]
We seem to go back and forth on this, and while wasm3 seems to be better for the low cold start penalty it does end up slower than wasmtime in execution in long running wasmcloud hosts. Perhaps now is the time to make our released wasmcloud binary use wasmtime instead.

**Comment by autodidaddict** [comment]
"slower" than wasmtime is a very subjective number. wasm3 per-function-call latency via wapc is a matter of micros.

**Comment by autodidaddict** [comment]
if we're going to change how we release then we essentially add the engine to the matrix, so that we build for OS+CPU+engine and release `wasmcloud-wasm3` and `wasmcloud-wasmtime`, etc. Or we continue just releasing the default wasm3 which is the better general purpose engine and let those who want wasmtime choose it as a feature-flag when they cargo install.

**Review by autodidaddict — DISMISSED** [review]

**Comment by brooksmtownsend** [comment]
Apparently by merging the wasmcloud-host version it dismissed your review @autodidaddict

**Review by autodidaddict — APPROVED** [review]

**Pull request merged**
