### PR TITLE
fix(washboard-ui): reorganize components table view

### LINKED ISSUE #2626: [BUG] washboard provides strange Count parameter
### Affected project(s)

- [ ] documentation
- [ ] examples
- [ ] wasmCloud host
- [X] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [ ] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Describe the bug

image

It appears that the "count" is both a duplicated heading and possibly wrong. I haven't taken a look at the code yet, but 56 seems suspiciously like that's counting the number of characters in a host ID.

### Steps to reproduce

1. Run wash new component to generate a hello-world project
2. run `wash up -d` to launch wasmCloud
3. cd component && wash build
4. wash app deploy ./wadm.yaml
5. wash ui
6. visit localhost:3030
7. see odd count

### Expected behavior

I think the `count` field should be removed, and in the dropdown of the component view we should be able to copy the host ID, not the number running on a specific host.
image

### Environment

- OS: [e.g. Linux, MacOS]
- Shell [e.g. bash, zsh, powershell]
- wasmcloud Version [e.g. 0.81.0]

### Screenshots / Logs / Additional context

_No response_

### PR DESCRIPTION
**Pull request by Ruby-rc**
## Feature or Problem

Updated the displayed parameters in the components-table

- add ID.
- removed max count.
- changed the order of the table headers.

image

## Related Issues

closes #2626

### CODE REVIEW

**Comment by lachieh** [comment]
Thanks, @Ruby-rc! Looks great!

It looks like you'll need to signoff your commit and then force push to this branch, which you can do by running the following:
```
git rebase HEAD~1 --signoff
git push --force-with-lease origin fix/ui-components-table-view
```

**Review by lachieh — APPROVED** [review]

**Comment by Ruby-rc** [comment]
> Thanks, @Ruby-rc! Looks great!
> 
> It looks like you'll need to signoff your commit and then force push to this branch, which you can do by running the following:
> 
> ```
> git rebase HEAD~1 --signoff
> git push --force-with-lease origin fix/ui-components-table-view
> ```

Thanks for your reminder, It has been revised.

But there was a previous incorrect signoff not sure if it had any effect.

**Comment by Ruby-rc** [comment]
@lachieh 

I removed the countInstances function from this pr, a bit unsure if it was written for a specific purpose.

Is that acceptable?

**Comment by lachieh** [comment]
Looks good! 👍 

The `countInstances` function was incorrect anyway, so you're good to delete it.

Thanks again for the PR!

**Pull request merged**
