### PR TITLE
fix(control-interface)!: wrong data returned from provider auction

### PR DESCRIPTION
**Pull request by vados-cosmonic**

### CODE REVIEW

**Review by ricochet — APPROVED** [review]
Possible to add tests where this is used? Approving since these are just getter updates but we need coverage in a follow-up.

**Comment by vados-cosmonic** [comment]
@ricochet Sure, I'll add that right now then -- the getters are all new

**Comment by joonas** [comment]
@vados-cosmonic since the getters are new, and you're essentially just fixing a bug, should this really be classified as a breaking change? I don't feel like it is

**Comment by vados-cosmonic** [comment]
Yeah it doesn't *have* to be -- but given that the previous functionality was semantically wrong I was thinking it would be a big change sematics-wise. 

Either way the plan is to `yank` the old version though!

**Review by thomastaylor312 — APPROVED** [review]

**Pull request merged**
