### PR TITLE
fix: Go http hello world template

### LINKED ISSUE #3829: [BUG] project templating for go examples incomplete
### Affected project(s)

- [ ] documentation
- [X] examples
- [ ] wasmCloud host
- [X] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [ ] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Describe the bug

Go examples with project-generate.toml do not completely template all of the necessary areas a project needs to be initialized.

- go.mod to github repo url
- wasmcloud.toml fields for name and destination
- go imports for gen

### Steps to reproduce

`wash new component hello --template-name hello-world-tinygo`

### Expected behavior

No references to wasmcloud/examples/go/components...

### Environment

n/a

### Screenshots / Logs / Additional context

_No response_

### PR DESCRIPTION
**Pull request by lxfontes**
closes #3829

Update "http-hello-world" references to the user-defined "project-name".

Sample Run

Screenshot 2024-12-13 at 1 28 11 PM

### CODE REVIEW

**Comment by lxfontes** [comment]
Screenshot 2024-12-13 at 1 44 34 PM
CI is not going thru the `wash new` flow for examples. is there a magic incantation or is it by design?

**Comment by ricochet** [comment]
By design it's running wash build and not wash new. This is where using examples to create templates is somewhat problematic.

**Comment by lxfontes** [comment]
using this opportunity to move the template over to `/go`, and being specific about what is an example / template.
https://github.com/wasmCloud/go/pull/40

**Comment by joonas** [comment]
Given that wasmCloud/go#40 merged, this should probably be either closed or changed to update the [`favorites.toml`](https://github.com/wasmCloud/wasmCloud/blob/main/crates/wash-lib/src/generate/favorites.toml) references over to the new location.

**Comment by lxfontes** [comment]
closing in favour of moving the template over to go repo

**Pull request closed without merging**
