### PR TITLE
feat: support multiple label key-value pairs

### PR DESCRIPTION
**Pull request by hanshal101**

### CODE REVIEW

**Comment by hanshal101** [comment]
Hey @connorsmith256 can you guide me in the process of signing off a commit.

**Comment by ericgregory** [comment]
@hanshal101 Hey Hanshal! You can sign a commit with the `-s` or `--signoff` flag, like this:

`git commit -m "Message here" --signoff`

The DCO details contain instructions for rebasing to add signoff to previous work: https://github.com/wasmCloud/wasmCloud/pull/1779/checks?check_run_id=23189294391

**Comment by hanshal101** [comment]
Thanks @ericgregory . Do I need to add my github details during the signoff?

**Comment by ericgregory** [comment]
> Thanks @ericgregory . Do I need to add my github details during the signoff?

@hanshal101 As long as your user [name](https://docs.github.com/en/get-started/getting-started-with-git/setting-your-username-in-git) and [email](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-email-preferences/setting-your-commit-email-address#setting-your-commit-email-address-in-git) are configured for git, the `--signoff` flag will add those automatically :)

**Comment by vados-cosmonic** [comment]
Hey @hanshal101 I ended up doing this in https://github.com/wasmCloud/wasmCloud/pull/2140 so I think we can close this PR! Please let me know if there's something I missed :)

**Pull request closed without merging**
