### PR TITLE
Adding clap-markdown feature into arg parsing logic of wasmCloud host

### PR DESCRIPTION
**Pull request by vangourd**
## Feature or Problem
WasmCloud Host should utilize the same `clap-markdown` capability implemented in wash-cli  in order to auto-generate docs. Additionally docs should exist on how to update the documentation for copy into wasm docs. 

## Related Issues
https://github.com/wasmCloud/wasmcloud.com/issues/597

## Release Information
next

## Consumer Impact
- wasm host binary invocations and arg parsing
- wasm documentation output

### CODE REVIEW

**Comment by vangourd** [comment]
I believe this is ready for review.

It can be tested with `./target/debug/wasmcloud --help-markdown` locally after a build.

**Comment by vados-cosmonic** [comment]
Hey @vangourd thanks for submitting this PR! We've definitely used this before (IIRC this is the setup that @ericgregory uses to build our docs) -- would you mind if I jump in here and rebase/handle some of the lint issues?

**Comment by vangourd** [comment]
Don't mind at all please. Any assistance if welcome @vados-cosmonic

**Review by vados-cosmonic — APPROVED** [review]
LGTM :rocket:

**Pull request merged**
