### PR TITLE
fix: add project-generate.toml to dog-fetcher template

### LINKED ISSUE #2437: [BUG] dog-fetcher template missing project-generate.toml
### Affected project(s)

- [ ] documentation
- [X] examples
- [ ] wasmCloud host
- [ ] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [ ] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Describe the bug

When you try to start a new project from the `examples/rust/components/dog-fetcher` template with `wash new component`, you get this error:

```shell
Failed to generate project

Caused by:
    0: Invalid template folder: Required configuration file `project-generate.toml` is missing.
    1: ⛔   File not found within template 
```

### Steps to reproduce

- Run `wash new component`
- Select `rust-dog-fetcher` option

### Expected behavior

Successful creation of new component from template

### Environment

- OS: macOS
- Shell: zsh
- wash version: wash 0.29.2

### Screenshots / Logs / Additional context

_No response_

### PR DESCRIPTION
**Pull request by ericgregory**
Resolves #2437

### CODE REVIEW

**Review by vados-cosmonic — APPROVED** [review]
LGTM :rocket:

**Comment by vados-cosmonic** [comment]
Hey @ericgregory also there's a little bug in your conventional commit -- `fix: ` is missing a space.

I'd also recommend removing the changes to `Cargo.lock` for this PR so that we can get it merged with just reviews by example maintainers!

**Comment by ericgregory** [comment]
> Hey @ericgregory also there's a little bug in your conventional commit -- `fix: ` is missing a space.
> 
> I'd also recommend removing the changes to `Cargo.lock` for this PR so that we can get it merged with just reviews by example maintainers!

Thanks, updated!

**Comment by vados-cosmonic** [comment]
Yeah... it might be too late -- I still see host maintainers required, but maybe the merge will work once test pass.

**Pull request merged**
