### PR TITLE
Renamed control-interface to wasmcloud-control-interface

### PR DESCRIPTION
**Pull request by brooksmtownsend**
See title.

While I was in the tests directory, I noticed some generated HTTP code, so I removed it and instead used the shared actor interface types.

### CODE REVIEW

**Review by autodidaddict — APPROVED** [review]

**Comment by laodev1** [comment]
First off fellas, THIS IS THE COOLEST THING I HAVE EVER SEEN! I can't wait to realize the promise of contract driven development! 🚀  I am going through the wash tutorial and have an error that I believe relates to this recent rename of the control-interface? Forgive me if that is wrong, I am not read in on OCI registry yet. 
image

My apologies for not being able to contribute a pull request that fixes it. My kung fu isn't that strong....yet 😉

**Comment by autodidaddict** [comment]
This actually looks like the echo actor,  or at least that version,  isn't in the azure container registry

**Comment by laodev1** [comment]
I didn't know if it was the whole actor or just those dependencies. We need a hashtag: **#nomoreboilerplate**

**Comment by brooksmtownsend** [comment]
@laodev1 It does look like that version of the echo actor isn't present in our AzureCR. I'll check our example actor release CICD this morning and reply to this issue again with the correct version. Thanks for the feedback #nomoreboilerplate!

**Comment by brooksmtownsend** [comment]
@laodev1 Looking into it, it appears that our echo actor is published at `wasmcloud.azurecr.io/echo:0.2.0`. Try that version again with your example

**Comment by brooksmtownsend** [comment]
Oh and to address your previous concern, you may just need to update `wash` to the latest version to see those changes, the old version should still work alright. You can do that directly with
```
cargo install wash-cli --force
```
Or if you're building from source, just pull in the latest changes to `main`.

**Comment by laodev1** [comment]
@brooksmtownsend working like a charm! Thanks for everything guys. This is really compelling stuff!

**Pull request merged**
