### PR TITLE
fix(build): Fix the go version for wash build

### PR DESCRIPTION
**Pull request by ritesh089**
## Feature or Problem
Fixing the go version in custom template for wash build to work

### CODE REVIEW

**Comment by vados-cosmonic** [comment]
Hey @ritesh089 when I run `wash build` on the code in `golang/providers/custom-template` *and* `golang/providers/custom-template/component` they both successfully produce the provider and component. 

I'm running:
- `wit-bindgen-wrpc-cli` v0.1.3
- `wash` v0.29.2

What error were you seeing? am I running it the wrong way perhaps?

**Comment by ritesh089** [comment]
I got the below error running wash build on the component:
```
wash build
error: requires go version 1.18 through 1.21, got go1.22
```

wash 0.29.2

**Comment by vados-cosmonic** [comment]
AH! What version of `tinygo` are you using? You're actually getting that error from `tinygo`.

Here's what I'm running

```
tinygo version 0.31.2 linux/amd64 (using go version go1.22.4 and LLVM version 17.0.1)
```

**Comment by ritesh089** [comment]
> AH! What version of `tinygo` are you using? You're actually getting that error from `tinygo` I think!
> 
> Here's what I'm running
> 
> ```
> tinygo version 0.31.2 linux/amd64 (using go version go1.22.4 and LLVM version 17.0.1)
> ```

tinygo version 0.29.0 darwin/amd64 (using go version go1.22.3 and LLVM version 15.0.0)

**Comment by vados-cosmonic** [comment]
Ah would you mind upgrading your version of tinygo?

**Comment by brooksmtownsend** [comment]
Yeah we should support 1.22 just fine

**Comment by ritesh089** [comment]
I still had to update it to go 1.22.3 to build successfully .

**Comment by vados-cosmonic** [comment]
Hmnn I'm still a little confused at what could be requiring the go mod to be so specific... But since the version in there is a minimum, I don't think there's too much of a problem with updating the minimum required version.

**Review by vados-cosmonic — APPROVED** [review]
LGTM :rocket:

**Pull request merged**
