### PR TITLE
fix(infra): lattice prefix ENV var

### PR DESCRIPTION
**Pull request by vados-cosmonic**

### CODE REVIEW

**Review by joonas — CHANGES_REQUESTED** [review]
This chart is deprecated, could you try using [`wasmcloud-host`](https://github.com/wasmCloud/wasmCloud/tree/main/charts/wasmcloud-host) ([in ghcr](https://github.com/wasmCloud/wasmCloud/pkgs/container/charts%2Fwasmcloud-host)) instead?

**Comment by vados-cosmonic** [comment]
Ahh thanks @joonas  for noting that this chart is deprecated -- can I delete it now?

**Comment by joonas** [comment]
> Ahh thanks @joonas for noting that this chart is deprecated -- can I delete it now?

It was removed in https://github.com/wasmCloud/wasmCloud/pull/3646

**Comment by vados-cosmonic** [comment]
Ah OK! If this was removed already then will close this PR! thanks

**Pull request closed without merging**
