### PR TITLE
chore(ci): tighten github actions workflow permissions

### PR DESCRIPTION
**Pull request by joonas**
## Feature or Problem

Doing another round of reviewing the various workflows and their permissions to tighten things down.

### CODE REVIEW

**Review by brooksmtownsend — APPROVED** [review]
LGTM as long as I'm not missing anything on the TS side @lachieh

**Comment by joonas** [comment]
I ended up doing a few rounds of changes with the TS tooling based on errors, so I think we should be in a good spot with that 👍

**Comment by lachieh** [comment]
Yeah looks good to me, they should all be read except for the app-release which is the only one that uses the GH release flow 👍🏻

**Comment by joonas** [comment]
> Yeah looks good to me, they should all be read except for the app-release which is the only one that uses the GH release flow 👍🏻

Exactly, though when you're calling workflows from other workflows where the "sub-workflows" need more permissions than the workflow calling them, you'll need to make sure that the calling workflow requests the same permissions as the workflow it's calling, which is what I ended up wrestling with a bit

**Pull request merged**
