### PR TITLE
docs: fix broken links

### PR DESCRIPTION
**Pull request by connorsmith256**
## Feature or Problem
This copies over a change from https://github.com/wasmCloud/capability-providers/pull/268 to update the README to fix a few broken links

### CODE REVIEW

**Review by rvolosatovs — CHANGES_REQUESTED** [review]
This should be done via a subtree merge instead

**Comment by rvolosatovs** [comment]
See https://github.com/wasmCloud/wasmCloud/pull/676

**Comment by rvolosatovs** [comment]
Sorry, I just tried to be fast to prevent merge. Making manual changes like this will complicate subtree merges in the future

**Comment by connorsmith256** [comment]
I forgot we did a subtree 👍

**Pull request closed without merging**
