### PR TITLE
feat(*): Updates code of conduct to link to CNCF CoC

### PR DESCRIPTION
**Pull request by thomastaylor312**
Since we are moving to incubating, we should update to link out to the CNCF code of conduct. The CNCF CoC is based on the same contributor covenant we were currently pointing at so this change is minimal. However, we should make sure we at least get a majority vote from org maintainers before merge

### CODE REVIEW

**Review by ricochet — APPROVED** [review]

**Review by brooksmtownsend — APPROVED** [review]
Sounds good to me 👍🏻

**Review by jordan-rash — APPROVED** [review]
❤️

**Review by lachieh — APPROVED** [review]

**Review by LiamRandall — APPROVED** [review]
lgtm!

**Review by LiamRandall — APPROVED** [review]
LGTM!

**Pull request merged**
